services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reto-web
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    working_dir: /app/src
    environment:
      FLASK_ENV: development
      DATABASE_URI: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    command: ["python", "run.py"]

  db:
    image: postgres:15
    container_name: reto-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
